### ISSUE TITLE
About the 2D Data

### ISSUE THREAD

**Issue by ardianumam** [wangzy22/TAP#4]
Hi,

Thanks for the great work! I've read the paper and it is mentioned that this work uses 12 surrounding 2D images generated
by [MVCNN](https://github.com/suhangpro/mvcnn). I have some questions as follows.
1. If I'm not wrong, the generated 2D images are from mesh shapes (CAD file). Is this right?
2. If no (1) is right, what if our dataset does not have CAD files (mesh shapes), that is, only point clouds of the shapes are available. How does the proposed method work for such dataset?

Many thanks

**Comment by wangzy22** [comment]
Hi, thanks for your interest in our work and sorry for the late reply.

1. Yes, the generated 2D images are from meshes.
2. In that case, maybe you can render projected images from point cloud via Neural Rendering / 3D Gaussian Splatting / other learning-based methods such as [PointClipV2](https://github.com/yangyangyang127/PointCLIP_V2). The principle is that you produce projected images corresponding to camera poses and the geometry relationship is accurate.

Hopefully these information would help!
