### ISSUE TITLE
missing data

### ISSUE THREAD

**Issue by HilbertXu** [wangzy22/TAP#6]
Hi,

Thanks for your great work! 
When I was trying your work, I noticed that the download link of the 12-view images from MVCNN is not valid anymore, is there any other way to obtain these images? 

Cheers,
Yucheng

**Comment by wangzy22** [comment]
Hi, thanks for your interest in our work and sorry for the late reply.

I've uploaded the dataset to Tsinghua Cloud and updated the download [link](https://cloud.tsinghua.edu.cn/f/dd9ef45fb00e427eae23/?dl=1). Thanks for pointing out the invalidity of the previous link.
